version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lala_rental
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm start

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lala_rental
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: